---
env:
  browser: true
  commonjs: true
  es6: true

extends: eslint:recommended

parserOptions:
  ecmaVersion: 9
  sourceType: module

rules:
  valid-jsdoc:
  - warn
  - requireParamDescription: false
    requireReturnDescription: false
    requireReturn: false
